export function get(object: any, path: any): string;
export function set(object: any, path: any, value: any): string;
export function getToggle(object: any, key: any, placeholder: any): string;
export function json(json: any, block: any): any;
export function attributes(attributes: any): Handlebars.SafeString;
export function replace(text: any, search: any, replace: any): any;
export function stringify(object: any, format: any): Handlebars.SafeString;
export function markdown(text: any): Handlebars.SafeString;
export function ansi(text: any): Handlebars.SafeString;
export function eq(first: any, second: any, block: any): any;
export function ne(first: any, second: any, block: any): any;
export function and(...args: any[]): any;
export function or(...args: any[]): any;
export function indexof(propertyOrValue: any, haystack: any, block: any): any;
export function concat(...args: any[]): string;
export function lowercase(value: any): any;
export function uppercase(value: any): any;
export function regexReplace(text: any, search: any, flags: any, replace: any): any;
export function stripHost(URL: any): any;
export function camelize(value: any): any;
export function sanitize(value: any, replace: any): any;
export function modulus(index: any, mod: any, result: any, block: any): any;
export function debugString(object: any): Handlebars.SafeString;
export function debug(...args: any[]): Handlebars.SafeString;
export function even(index: any, even: any, odd: any): any;
export function gt(value: any, value2: any, block: any): any;
export function gte(value: any, value2: any, block: any): any;
export function lt(value: any, value2: any, block: any): any;
export function lte(value: any, value2: any, block: any): any;
export function forLoop(from: any, to: any, block: any): string;
export function notIn(needle: any, haystack: string, block: any): any;
export function inHelper(needle: any, haystack: string, block: any): any;
export function falseHelper(...args: any): boolean;
export function trueHelper(...args: any): boolean;
export function count(value: any): boolean;
export function hasSubStr(text: any, subString: any, block: any): any;
export function sumArgs(...args: any[]): any;
export function customFormatPrice(number: any, thousands: string, decimals: string, length: any, currency: string): string;
export function sumArray(array: any[], key: string): any;
export function isNegative(number: any, block: any): any;
export function formatWeight(number: any, decimal: string, length: any): string;
export function base1Index(index: any): any;
export function formatDate(date: any, zone: any, dateStyle: any, timeStyle: any): string;
import Handlebars = require("handlebars");
